name: Build Suyula Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 强制使用自带所有零件的稳定老车间 v5.3
    container: espressif/idf:release-v5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          git config --global --add safe.directory /__w/xiaozhi-esp32/xiaozhi-esp32
          
          # 暴力破解：强行把源码里要求 5.5.2 的限制降级，骗过编译器！
          sed -i 's/>=5.5.2/>=5.2/g' main/idf_component.yml
          sed -i 's/>=5.4.0/>=5.2/g' main/idf_component.yml
          
          # 直接编译
          python3 scripts/release.py xingzhi-cube-1.54tft-wifi -c config.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: suyula-firmware
          path: build/merged-binary.bin
